### ISSUE TITLE
404 Not Found on mobile brower

### ISSUE THREAD

**Issue by Stearinrin** [ueckoken/KokenWiki#54] opened 2020-06-10 03:33 UTC
I haven't been able to browse the wiki on my mobile Safari browser for a couple of months.
The same problem seems to occur on all pages.

Environment:
- iOS 13.5.1, iPhone 11 Pro

**Comment by otariidae** [comment] 2020-06-10 05:03
404 is intentional because you are not logged in.
But the log-in button is unexpectedly not shown.
This is caused by #44 which upgrades jQuery to 3.5.0.

This will be fixed by upgrading jQuery to 3.5.1
ref: http://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

Or also fixed by upgrading Bootstrap
Ref https://github.com/twbs/bootstrap/issues/30553

**Closed** 2020-06-10 05:03 UTC
Labels: bug

**Comment by otariidae** [comment] 2020-06-10 05:07
Fixed.
Thanks for reporting the issue.
